# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-30 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tornillo',
            name='Tipomaterial',
        ),
        migrations.AddField(
            model_name='tornillo',
            name='diametro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalogo.diametro'),
        ),
        migrations.AddField(
            model_name='tornillo',
            name='tipomaterial',
            field=models.ManyToManyField(help_text='Seleccione un tipo de material para este tornillo', to='Catalogo.TipoMaterial'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Codigo particular para el tornillo en todo el inventario', primary_key=True, serialize=False),
        ),
    ]
